var args=process.argv,pduSend=process.argv.slice(2)[0],wapTokens={type:function(a){return 6==a?"Push":"unknown"},WSP:function(a){for(var c,b="",e=[],d={};a.length;)c=parseInt(a.shift(),16),0===c&&d.octets&&d.pos++,0<c&&32>c?(d.octets&&e.push(d),d={key:"",value:"",pos:0,octets:c},31===c&&(d.octets=parseInt(a.shift(),16)),0===e.length&&(d.key="Content-Type")):31<c&&128>c?(d.value+=String.fromCharCode(c),d.pos++):127<c&&(c&=127,1===c?d.value+="; charset=":48===c?d.value+="application/vnd.wap.slc":46===
c?d.value+="application/vnd.wap.sic":106===c&&(d.value+="UTF-8"),d.pos++),d.pos>=d.octets&&(e.push(d),d={key:"",value:"",pos:0,octets:0});for(a=0;a<e.length;a++)b+=e[a].key+": "+e[a].value;return b},WBXML:function(a){var c,b="";for(c=0;c<a.length;++c)b+=a[c];$.ajax({async:!1,cache:!1,data:{octets:b},timeout:1E3,url:"wbxml.pl",success:function(e){b=e.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/&/g,"&amp;")}});if(!b.match(/&/))for(b+=" (Could not be decoded, try ASCII decoding)";a.length;)b+=
String.fromCharCode(parseInt(a.shift(),16));return b}},gsm7bit={0:"@",1:"\u00a3",2:"$",3:"\u00a5",4:"\u00e8",5:"\u00e9",6:"\u00f9",7:"\u00ec",8:"\u00f2",9:"\u00c7",10:"\n",11:"\u00d8",12:"\u00f8",13:"\r",14:"\u00c5",15:"\u00e5",16:"\u0394",17:"_",18:"\u03a6",19:"\u0393",20:"\u039b",21:"\u03a9",22:"\u03a0",23:"\u03a8",24:"\u03a3",25:"\u0398",26:"\u039e",28:"\u00c6",29:"\u00e6",30:"\u00df",31:"\u00c9",32:" ",33:"!",34:'"',35:"#",36:"\u00a4",37:"%",38:"&",39:"'",40:"(",41:")",42:"*",43:"+",44:",",45:"-",
46:".",47:"/",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",58:":",59:";",60:"<",61:"=",62:">",63:"?",64:"\u00a1",65:"A",66:"B",67:"C",68:"D",69:"E",70:"F",71:"G",72:"H",73:"I",74:"J",75:"K",76:"L",77:"M",78:"N",79:"O",80:"P",81:"Q",82:"R",83:"S",84:"T",85:"U",86:"V",87:"W",88:"X",89:"Y",90:"Z",91:"\u00c4",92:"\u00d6",93:"\u00d1",94:"\u00dc",95:"\u00a7",96:"\u00bf",97:"a",98:"b",99:"c",100:"d",101:"e",102:"f",103:"g",104:"h",105:"i",106:"j",107:"k",108:"l",109:"m",110:"n",
111:"o",112:"p",113:"q",114:"r",115:"s",116:"t",117:"u",118:"v",119:"w",120:"x",121:"y",122:"z",123:"\u00e4",124:"\u00f6",125:"\u00f1",126:"\u00fc",127:"\u00e0",27:{10:"\n",20:"^",40:"{",41:"}",47:"\\",60:"[",61:"~",62:"]",64:"|",101:"&#8364;"}},tokens={Number:function(a,c,b){var e="";if(b&&80===b.ToN)e=decode7Bit(a);else{for(b=0;b<a.length;++b)e+=reverse(a[b]);if(e.match(/\D$/)||c&&e.length>c)a=/(.)$/.exec(e),e=e.substring(0,e.length-1),a&&a[1]&&"F"!==a[1]&&(e+="(VIOLATION!)")}return e},ToA:function(a){a=
parseInt(a,16);var c=a&112,b=a&15,e="";e=(0===c?e+"Unknown type of address":16===c?e+"International number":32===c?e+"National number":48===c?e+"Network specific number":64===c?e+"Subscriber number":80===c?e+"Alphanumeric, (coded according to GSM TS 03.38 7-bit default alphabet)":96===c?e+"Abbreviated number":112===c?e+"Reserved for extension":e+"Reserved type of address")+", ";e=0===b?e+"Unknown":1===b?e+"ISDN/telephone numbering plan (E.164/E.163)":3===b?e+"IData numbering plan (X.121)":4===b?e+
"Telex numbering plan":8===b?e+"National numbering plan":9===b?e+"Private numbering plan":10===b?e+"ERMES numbering plan (ETSI DE/PS 3 01-3)":15===b?e+"Reserved for extension":e+"Reserved numbering plan";0===(a&128)&&(e+=" (VIOLATION: Highest bit should always be set!)");return{ToN:c,NPI:b,info:e}},ToM:function(a){a=parseInt(a,16);var c="",b=[],e=!1,d=!1,f=null,h=!1;0===(a&1)?(c+="SMS-DELIVER",e=!0):1===(a&1)?(c+="SMS-SUBMIT",d=!0):console.debug(a,padwZeros(a.toString(2)));a&128&&b.push("TP-RP (Reply path exists)");
a&64&&(h=!0,b.push("TP-UDHI (User data header indicator)"));if(d){a&32&&b.push("TP-SRR (Status report request)");var g=a&24;0!==g&&(8===g?(f="enhanced",b.push("TP-VPF (Validity Period Format): enhanced format")):16===g?(f="relative",b.push("TP-VPF (Validity Period Format): relative format")):24===g&&(f="absolute",b.push("TP-VPF (Validity Period Format): absolute format")));0===(a&4)&&b.push("TP-RD (Reject duplicates)")}else e&&(a&32&&b.push("TP-SRI (Status report indication)"),0===(a&4)&&b.push("TP-MMS (More messages to send)"));
b.length&&(c+=", Flags: "+b.join(", "));return{type:e?"deliver":d?"submit":"",TP_UDHI:h,TP_VPF:f,info:c}},PID:function(a){var c=parseInt(a,16);a="";var b=c&192;0===b?(b=c&31,c&32?(a+="Telematic interworking (Type: ",a=(0===b?a+"implicit":1===b?a+"telex":2===b?a+"group 3 telefax":3===b?a+"group 4 telefax":4===b?a+"voice telephone - speech conversion":5===b?a+"ERMES - European Radio Messaging System":6===b?a+"National Paging System":7===b?a+"Videotex - T.100/T.101":8===b?a+"teletex, carrier unspecified":
9===b?a+"teletex, in PSPDN":10===b?a+"teletex, in CSPDN":11===b?a+"teletex, in analog PSTN":12===b?a+"teletex, in digital ISDN":13===b?a+"UCI - Universal Computer Interface, ETSI DE/PS 3 01-3":16===b?a+"message handling facility known to the SC":17===b?a+"public X.400-based message handling system":18===b?a+"Internet E-Mail":24<=b&&30>=b?a+"SC specific value":31===b?a+"GSM mobile station":a+"reserved")+")"):(a+="SME-to-SME protocol",0<b&&(a+=" (Unknown bitmask: "+b.toString(2)+"- in case of SMS-DELIVER these indicate the SM-AL protocol being used between the SME and the MS!)"))):
64===b?(c&=63,a=0<=c&&7>=c?a+("Short Message Type "+c):31===c?a+"Return Call Message":61===c?a+"ME Data download":62===c?a+"ME De-personalization Short Message":63===c?a+"SIM Data download":a+"reserved"):128===b?a+="reserved":192===b&&(a+="SC specific use");return a},DCS:function(a){var c=parseInt(a,16);a="";var b="default",e=c&240;if(0<=e&&48>=e){a+="General Data Coding groups, ";a=(c&32?a+"compressed":a+"uncompressed")+", ";var d=c&12;0===d?a+="default alphabet":4===d?(a+="8 bit data",b="8bit"):
8===d?(a+="UCS2 (16 bit)",b="ucs2"):12===d&&(a+="reserved alphabet")}else 64<=e&&176>=e?a+="Reserved coding groups":192===e?a+="Message Waiting Indication Group: Discard Message, ":208===e?a+="Message Waiting Indication Group: Store Message, standard encoding, ":224===e?a+="Message Waiting Indication Group: Store Message, UCS2 encoding, ":240===e&&(a+="Data coding/message class, ",c&8&&(a+="(VIOLATION: reserved bit set, but should not!), "),c&4?(a+="8 bit data",b="8bit"):a+="Default alphabet");if(0<=
e&&48>=e||240===e)a+=", ",0<=e&&48>=e&&0===(c&16)&&(a+=" no message class set (but given bits would be: "),d=c&3,a+="Class "+d+" - ",0===d?a+="immediate display":1===d?a+="ME specific":2===d?a+="SIM specific":3===d&&(a+="TE specific"),a+=")";192<=e&&224>=e&&(a=(c&8?a+"Set Indication Active":a+"Set Indication Inactive")+", ",c&4&&(a+="(reserved bit set, but should not!), "),c&=3,0===c?a+="Voicemail Message Waiting":1===c?a+="Fax Message Waiting":2===c?a+="E-Mail Message Waiting":3===c&&(a+="Other Message Waiting (not yet standardized)"));
return{alphabet:b,info:a}},SCTS:function(a){var c;for(c=0;7>c;++c)a[c]=reverse(a[c]);c="";c=70>parseInt(a[0],10)?c+"20":c+"19";c+=a[0]+"-"+a[1]+"-"+a[2]+" "+a[3]+":"+a[4]+":"+a[5]+" GMT ";a=parseInt(a[6],10);a&128?(a&=127,c+="-"):c+="+";return c+a/4},UDL:function(a,c){var b=parseInt(a,16),e=b;var d="default"===c?Math.ceil(70*b/80):b;"ucs2"===c&&(e=d/2);return{septets:b,octets:d,info:e+" characters, "+d+" bytes"}},UDHL:function(a,c){var b=parseInt(a,16),e=0;"default"===c&&(e=8*(b+1),e=7*Math.ceil(e/
7)-e);return{length:b,padding:e,info:b+" bytes"}},UDH:function(a){for(var c=[],b={},e=[],d="",f=!1,h=!1,g=[],k=[];a.length;)d=parseInt(a.shift(),16),void 0===b.IEI?b.IEI=d:void 0===b.IEDL?b.IEDL=d:(void 0===b.IED&&(b.IED=[]),b.IED.push(d),b.IED.length>=b.IEDL&&(c.push(b),b={}));for(a=0;a<c.length;++a)if(5===c[a].IEI)b=256*c[a].IED[0]+c[a].IED[1],5505===b?b+=" (Ring Tone)":5506===b?b+=" (Operator Logo)":5507===b?b+=" (Group Graphic - CLI Logo)":9200===b?b+=" (Connectionless WAP browser proxy server)":
9202===b?b+=" (Secure connectionless WAP browser proxy server)":9203===b?b+=" (Secure WAP Browser proxy server)":9204===b?b+=" (vCard)":9205===b?b+=" (vCalendar)":9206===b?b+=" (Secure vCard)":9207===b?b+=" (Secure vCalendar)":f=!0,d="WDP (Wireless Datagram Protocol): Destination port is "+b+", source port is "+(256*c[a].IED[2]+c[a].IED[3]),4!==c[a].IEDL&&(d+=" (VIOLATON: This Information Element should have exactly 4 bytes but says it has "+c[a].IEDL+" instead!)"),4!==c[a].IED.length&&(d+=" (VIOLATION: This Information Element should have exactly 4 bytes but actually has "+
c[a].IED.length+" instead!)"),e.push(d);else if(0===c[a].IEI)d="Concatenated message: reference number "+c[a].IED[0]+", part "+c[a].IED[2]+" of "+c[a].IED[1]+" parts",3!==c[a].IEDL&&(d+=" (VIOLATON: This Information Element should have exactly 3 bytes but says it has "+c[a].IEDL+" instead!)"),3!==c[a].IED.length&&(d+=" (VIOLATION: This Information Element should have exactly 3 bytes but actually has "+c[a].IED.length+" instead!)"),e.push(d);else if(10===c[a].IEI){h=!0;b=[];d=c[a].IED[2];1===(d&3)?
b.push("text-align: center"):2===(d&3)&&b.push("text-align: right");4===(d&12)?b.push("font-size: large"):8===(d&12)&&b.push("font-size: small");d&32&&b.push("font-style: italic");d&16&&b.push("font-weight: bold");d&64&&b.push("text-decoration: underline");d&128&&b.push("text-decoration: line-through");if(d=c[a].IED[3])1===(d&15)?b.push("color: darkGray"):2===(d&15)?b.push("color: darkRed"):3===(d&15)?b.push("color: GoldenRod"):4===(d&15)?b.push("color: darkGreen"):5===(d&15)?b.push("color: darkCyan"):
6===(d&15)?b.push("color: darkBlue"):7===(d&15)?b.push("color: darkMagenta"):8===(d&15)?b.push("color: gray"):9===(d&15)?b.push("color: white"):10===(d&15)?b.push("color: red"):11===(d&15)?b.push("color: yellow"):12===(d&15)?b.push("color: green"):13===(d&15)?b.push("color: cyan"):14===(d&15)?b.push("color: blue"):15===(d&15)&&b.push("color: magenta"),0===(d&240)?b.push("background-color: black"):16===(d&240)?b.push("background-color: darkGray"):32===(d&240)?b.push("background-color: darkRed"):48===
(d&240)?b.push("background-color: GoldenRod"):64===(d&240)?b.push("background-color: darkGreen"):80===(d&240)?b.push("background-color: darkCyan"):96===(d&240)?b.push("background-color: darkBlue"):112===(d&240)?b.push("background-color: darkMagenta"):128===(d&240)?b.push("background-color: gray"):144===(d&240)?b.push("background-color: white"):160===(d&240)?b.push("background-color: red"):176===(d&240)?b.push("background-color: yellow"):192===(d&240)?b.push("background-color: green"):208===(d&240)?
b.push("background-color: cyan"):224===(d&240)?b.push("background-color: blue"):240===(d&240)&&b.push("background-color: magenta");b.length?(c[a].markupOpen='<span style="'+b.join("; ")+'">',c[a].markupClose="</span>"):(c[a].markupOpen="",c[a].markupClose="");k.push(c[a]);g.push(function(n,l,m){l=l.substr(k[m].IED[0],k[m].IED[1]);return n.replace(new RegExp(l),k[m].markupOpen+l+k[m].markupClose)})}h&&e.push("has EMS formatting");return{wap:f,formatting:g,info:e.join("; ")}},UD:function(a,c,b,e){var d=
"";if("default"===c)d=decode7Bit(a,b);else if("ucs2"===c)for(;a.length;)c=a.shift()+a.shift(),d+=String.fromCharCode(parseInt(c,16));else for(d+="(",d=("8bit"===c?d+"unknown binary data":d+"unrecognized alphpabet")+", try ASCII decoding) ";a.length;)d+=String.fromCharCode(parseInt(a.shift(),16));if(e&&e.length)for(a=d,c=0;c<e.length;c++)d=e[c](d,a,c);return d},MR:function(a){return"00"===a?"Mobile equipment sets reference number":"0x"+a},VPrelative:function(a){a=parseInt(a,16);var c="";144>a?c=5*
(a+1)+" minutes":143<a&&168>a?c=30*(a-143)/60+12+" hours":167<a&&197>a?c=a-166+" days":186<a&&(c=a-192+" weeks");return c}};init();function init(){var a=pduSend;if(!a)return!1;a=constructOutput(a);a=JSON.stringify(a);console.log(a)}function constructOutput(a){var c=pduDecoder(a);if("object"===typeof c)for(a=0;a<c.length;++a);return c}function pduDecoder(a){return(a=splitter(a))?tokenizer(a):"Invalid PDU String!"}
function splitter(a){var c,b=[];for(c=0;c<a.length;c+=2){var e=a.substr(c,2);if(!e.match(/^[0-9A-F]{2}$/i))return null;b.push(e)}return b}
function tokenizer(a){var c=[],b,e={test:"al"};if(b=parseInt(a[0],16)){var d=a.slice(2,b+1);var f=a[1];var h=tokens.Number(d,void 0,tokens.ToA(f));var g=tokens.ToA(f).info;e.smsc_number=h;e.smsc_info=g}b+=1;f=tokens.ToM(a[b]);e.pdu_type=f.info;if("deliver"===f.type){b++;d=parseInt(a[b],16);b++;d&&(h=a.slice(b+1,b+1+Math.ceil(d/2)),g=a[b],c=tokens.Number(h,d,tokens.ToA(g)),h=tokens.ToA(g).info,e.sid_number=c,e.sid_info=h,b+=1+Math.ceil(d/2));d=a[b];e.protocol_identifier=tokens.PID(d);b++;var k=tokens.DCS(a[b]);
b++;a.slice(b,b+7);b+=6}else"submit"===f.type&&(b++,b++,d=parseInt(a[b],16),b++,d&&(h=a.slice(b+1,b+1+Math.ceil(d/2)),g=a[b],h=tokens.Number(h,d,tokens.ToA(g)),g=tokens.ToA(g).info,b+=1+Math.ceil(d/2)),d=a[b],b++,k=tokens.DCS(a[b]),c.push(function(){return"(hideable)Data Coding Scheme\t"+k.info}),f.TP_VPF&&(b++,"relative"!==f.TP_VPF&&f.TP_VPF.match(/^(absolute|relative)$/)&&(a.slice(b,b+7),b+=6)));b++;h=tokens.UDL(a[b],k.alphabet);c={};d={};f.TP_UDHI&&(b++,c=tokens.UDHL(a[b],k.alphabet),b++,d=tokens.UDH(a.slice(b,
b+c.length)),b+=c.length-1);b++;a=a.slice(b,b+h.octets-(c.length?c.length+1:0));d.wap?wapDecoder(a):tokens.UD(a,k.alphabet,c.padding,d.formatting);return e}function decode7Bit(a,c){var b,e=b="";c&&a.length&&(b=padwZeros(parseInt(a.shift(),16).toString(2)),b=b.substring(0,b.length-c));for(;a.length||parseInt(b,2);){b=getChar(a,b);var d=b[0];b=b[1];var f=gsm7bit[parseInt(d,2)];"object"===typeof f&&(b=getChar(a,b),d=b[0],b=b[1],f=f[parseInt(d,2)]);e+=f?f:""}return e}
function getChar(a,c){if(7===c.length)return[c,""];var b=padwZeros(parseInt(a.shift(),16).toString(2)),e=c.length+1,d=b.substr(e)+c;c=b.substr(0,e);return[d,c]}function reverse(a){return"string"===typeof a?a.substr(1,1)+a.substr(0,1):"00"}function padwZeros(a){for(;8>a.length;)a="0"+a;return a}
function wapDecoder(a){var c=0,b=[],e="";b.push("WSP Transaction ID\t0x"+a[c]);c++;b.push("Type\t"+wapTokens.type(a[c]));c++;var d=parseInt(a[c],16);c++;b.push("Wireless Session Protocol\t"+wapTokens.WSP(a.slice(c,c+d)));b.push("WAP Binary XML\t"+wapTokens.WBXML(a.slice(c+d)));for(a=0;a<b.length;++a)e+="<tr><td>"+b[a].replace(/\t/,"</td><td>")+"</td></tr>";return"<table><tbody>"+e+"</tbody></table>"}
function setForm(){var a=document.location.search.substr(1).split("&"),c={},b,e=/^TEXTAREA$/i,d=/^INPUT$/i,f=/^text$/i,h=/^(checkbox|radio)$/i,g=!1;for(b=0;b<a.length;++b){var k=a[b].split("=");c[k[0]]=c[k[0]]?[c[k[0]],k[1]]:k[1]}for(b in c)c.hasOwnProperty(b)&&(a=$('[name="'+b+'"]'),a.each(function(){this.tagName.match(e)||this.tagName.match(d)&&this.type.match(f)?(this.value=c[b],g=!0):this.tagName.match(d)&&this.type.match(h)&&this.value===c[b]&&(this.checked=!0,$(this).change(),g=!0)}));return g}
function cleanInput(a){a=$(a);a.val(a.val().replace(/\s/g,""))};
